### ISSUE TITLE
Tempo de permanência de veiculos no sistema da triagem

### ISSUE THREAD

**Issue by gubleo** [Craos/verticals-suite#2]
Registro de tempo dos eventos envolvidos no registro de vagas do sistema da triagem

- [x]  Registro de tempo para autorização da passagem
- [x] Registro de tempo de permanência do veículo no estacionamento

**Comment by OberdanBrito** [comment]
O recurso de tempo de permanência do veículo é obtido na leitura do totem de saída do visitante. Ao efetuar a leitura o sistema aciona o procedimento interno do banco de dados "acesso.autorizacao_raspberry_webservice" o mesmo insere novas linhas com as informações do veículo na tabela "triagem.autorizacao_saida"
![image](https://user-images.githubusercontent.com/19806411/74477779-b3f73f00-4e8a-11ea-9add-9363beeff843.png)
