### ISSUE TITLE
Preparar ambiente do servidor 2.17 para sistema da triagem

### ISSUE THREAD

**Issue by gubleo** [Craos/verticals-suite#5]
- [x] Dividir o repositório vllibs para colocar no servidor 2.17
- [x] Atualizar o repositório no servidor

**Comment by OberdanBrito** [comment]
- [ ] Dividir o repositório vllibs para colocar no servidor 2.17
- [ ] Atualizar o repositório no servidor

**Comment by OberdanBrito** [comment]
Finalizado com sucesso
